[package]
name = "notisystem"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
libc = "0.2.158"
libudev-sys = "0.1.4"
notify-rust = "4.11.1"
tokio = { version = "1.40.0", features = ["full"] }
udev = "0.9.0"
